AWSTemplateFormatVersion: "2010-09-09"
Description: "Website CloudFormation stack - Route53"

Parameters:
  Domain:
    Type: String
    Description: "The DNS name of an existing Amazon Route53 hosted zone, e.g. moduscreate.com"
    AllowedPattern: "(?!-)[a-z0-9-]{1,63}(?<!-)\\.(?!-)[a-z0-9-]{1,63}(?<!-)"
    ConstraintDescription: "Domain must be a valid DNS zone name. Allowed pattern: (?!-)[a-z0-9-]{1,63}(?<!-)\\.(?!-)[a-z0-9-]{1,63}(?<!-)"
  Subdomain:
    Type: String
    Description: "The DNS subdomain name, e.g. www"
    AllowedPattern: "(?!-)[a-z0-9-]{1,63}(?<!-)"
    ConstraintDescription: "Subdomain must be a valid DNS subdomain name. Allowed pattern: (?!-)[a-z0-9-]{1,63}(?<!-)"
  CloudFrontDistributionDomainName:
    Type: String
    Description: "The CloudFront distribution domain name"

Resources:
  Route53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: !Sub "${Domain}."
      Name: !Sub "${Subdomain}.${Domain}"
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2" # AWS constant: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        DNSName: !Ref "CloudFrontDistributionDomainName"
