AWSTemplateFormatVersion: "2010-09-09"
Description: "Website CloudFormation stack"

Parameters:
  Domain:
    Type: String
    Description: "The DNS name of an existing Amazon Route53 hosted zone, e.g. moduscreate.com"
    AllowedPattern: "(?!-)[a-z0-9-]{1,63}(?<!-)\\.(?!-)[a-z0-9-]{1,63}(?<!-)"
    ConstraintDescription: "Domain must be a valid DNS zone name. Allowed pattern: (?!-)[a-z0-9-]{1,63}(?<!-)\\.(?!-)[a-z0-9-]{1,63}(?<!-)"
  Subdomain:
    Type: String
    Description: "The DNS subdomain name, e.g. www"
    AllowedPattern: "(?!-)[a-z0-9-]{1,63}(?<!-)"
    ConstraintDescription: "Subdomain must be a valid DNS subdomain name. Allowed pattern: (?!-)[a-z0-9-]{1,63}(?<!-)"
  TemplatesDirectoryUrl:
    Type: String
    Description: "The URL to the templates directory, e.g. https://s3.amazonaws.com/awstatic.moduscreate.com/templates"

Resources:
  # Certificate
  CmcCloudFormationStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        Domain: !Ref "Domain"
        Subdomain: !Ref "Subdomain"
      TemplateURL: !Sub "${TemplatesDirectoryUrl}/template.certificate.yaml"

  # CloudFront OriginAccessIdentity
  CfoaiCloudFormationStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        Domain: !Ref "Domain"
        Subdomain: !Ref "Subdomain"
      TemplateURL: !Sub "${TemplatesDirectoryUrl}/template.cfoai.yaml"

  # Lambda
  LambdaCloudFormationStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - "CfoaiCloudFormationStack"
    Properties:
      Parameters:
        ReDirectUrls: "[[]]"
        ProjectS3Bucket: !Sub "${Subdomain}.${Domain}" 
      TemplateURL: !Sub "${TemplatesDirectoryUrl}/template.lambda.yaml"

  # S3
  S3CloudFormationStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - "CfoaiCloudFormationStack"
      - "LambdaCloudFormationStack"
    Properties:
      Parameters:
        Domain: !Ref "Domain"
        Subdomain: !Ref "Subdomain"
        CloudFrontOriginAccessIdentityId: !GetAtt ["CfoaiCloudFormationStack", "Outputs.CloudFrontOriginAccessIdentityId"]
        ProcessRedirectsLambdaFunction: !GetAtt ["LambdaCloudFormationStack", "Outputs.ProcessRedirectsLambdaFunctionOutput"]
      TemplateURL: !Sub "${TemplatesDirectoryUrl}/template.s3.yaml"
  
  # CloudFront
  CfCloudFormationStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - "CfoaiCloudFormationStack"
      - "CmcCloudFormationStack"
      - "S3CloudFormationStack"
      - "LambdaCloudFormationStack"
    Properties:
      Parameters:
        Domain: !Ref "Domain"
        Subdomain: !Ref "Subdomain"
        AcmCertificateArn: !GetAtt ["CmcCloudFormationStack", "Outputs.CertificateArn"]
        CloudFrontOriginAccessIdentityId: !GetAtt ["CfoaiCloudFormationStack", "Outputs.CloudFrontOriginAccessIdentityId"]
        OriginS3EndPoint: !GetAtt ["S3CloudFormationStack", "Outputs.WebsiteURL"]
      TemplateURL: !Sub "${TemplatesDirectoryUrl}/template.cloudfront.yaml"

  # Route 53
  R53CloudFormationStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - "CfCloudFormationStack"
    Properties:
      Parameters:
        Domain: !Ref "Domain"
        Subdomain: !Ref "Subdomain"
        CloudFrontDistributionDomainName: !GetAtt ["CfCloudFormationStack", "Outputs.CloudFrontDistributionDomainName"]
      TemplateURL: !Sub "${TemplatesDirectoryUrl}/template.route53.yaml"
Outputs:
  url:
    Value: !Sub "https://${Subdomain}.${Domain}"
    Description: "The website URL"
